### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by 110wuqu** [fangzheng0518/xianyu_spider#1]
2024-01-12 02:39:08 INFO:正在获取【餐饮券】关键字信息...
-32002 Client error: <> data: Selector [resourceId='com.taobao.idlefish:id/title'], method: None
 2024-01-12 02:39:33 ERROR:程序运行异常:{'code': -32002, 'data': "Selector [resourceId='com.taobao.idlefish:id/title']", 'method': 'wait'}
我在运行您的示例时出现了这个错误，可能是什么原因导致的呢

**Comment by 110wuqu** [comment]
at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:563)
	at android.app.UiAutomation.injectInputEvent(UiAutomation.java:773)
	at android.app.UiAutomation.injectInputEvent(UiAutomation.java:746)
	at com.github.uiautomator.stub.TouchController.injectEventSync(TouchController.java:38)
	at com.github.uiautomator.stub.TouchController.touchDown(TouchController.java:47)
	at com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:206)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:920)
, method: click
 2024-01-12 03:23:04 ERROR:程序运行异常:{'code': -32001, 'message': 'java.lang.SecurityException', 'data': 'java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission\n\tat android.os.Parcel.createExceptionOrNull(Parcel.java:2426)\n\tat android.os.Parcel.createException(Parcel.java:2410)\n\tat android.os.Parcel.readException(Parcel.java:2393)\n\tat android.os.Parcel.readException(Parcel.java:2335)\n\tat android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:563)\n\tat android.app.UiAutomation.injectInputEvent(UiAutomation.java:773)\n\tat android.app.UiAutomation.injectInputEvent(UiAutomation.java:746)\n\tat com.github.uiautomator.stub.TouchController.injectEventSync(TouchController.java:38)\n\tat com.github.uiautomator.stub.TouchController.touchDown(TouchController.java:47)\n\tat com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:206)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:920)\n'}
现在是提示这样一个错误

**Comment by 110wuqu** [comment]
搞定了

**Comment by l23abc0** [comment]
> 搞定了

如何搞定的阿大佬

**Comment by qq139885087** [comment]
可以用，不过效率很低

**Comment by Planetinaline** [comment]
> 搞定了
求教

**Comment by Planetinaline** [comment]
> 如何搞定的阿大佬
检查一下你的ATX服务器连接上了没
直接命令行前台启动一下看看 adb shell /data/local/tmp/atx-agent server

**Comment by stevenliuit** [comment]
2024-12-18 09:18:09 ERROR:程序运行异常:{'code': -32002, 'data': "Selector [resourceId='com.taobao.idlefish:id/title']", 'method': 'wait'}
 我也是报这个错误 咋解决啊
 adb shell /data/local/tmp/atx-agent server执行了 端口占用呢
